### ISSUE TITLE
Would be great if this worked with Spring Dependency Management plugin

### ISSUE THREAD

**Issue by madorb** [Splitties/refreshVersions#313]
Our projects use the Spring Dependency Management plugin for importing maven BOM files (as the native gradle functionality doesn't actually mimic the semantics of the maven approach, specifically overriding versions: https://github.com/gradle/gradle/issues/9160)
https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/

I am not gradle-smart enough to know if this is actually feasible or not, but this is unfortunately a blocker for us to fully move to the plugin.

**Comment by jmfayard** [comment]
Hello @madorb
sorry for the late reply. Could you describe what doens't work exactluy?

**Comment by Vampire** [comment]
You are talking about planting an apple tree vs. eating apples. The spring dependency management plugin is about consuming BOMs. The `java-platform` plugin and the issue you mentioned are about producing BOMs.

**Comment by LouisCAD** [comment]
refreshVersions works with BoMs, just use the version placeholder (`_`) for the version of the bom dependency (don't forget `platform` or `enforcedPlatform` !), and don't specify the versions of dependencies whose versions should be taken from said BoM.
