### ISSUE TITLE
Is it possible to have multiple versions.properties, e.g: versions-dev.properties and versions.properties

### ISSUE THREAD

**Issue by mochadwi** [Splitties/refreshVersions#451]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe

Previously we've a similar versioning approach for our dependency but placed in the `~/.gradle/versions.properties` (we also have on-premis CI server, to store this version)

We update the version inside `~/.gradle/versions.properties` by following triggers:

1. if merged
2. daily builds successful

## 💡 Describe the solution you'd like

Is it possible to distinguish the `versions.properties` based on our current environment, e.g: 

1. `versions-dev.properties` will use latest alpha development
2. `versions.properties` used if we ready to release, and to preserve and increment the stable versions if hotfixes occurred

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [ ] No
- [x] I'm not sure where to start 😄

**Comment by LouisCAD** [comment]
Look at the options available in the `refreshVersions { … }` block, you should already have what you're looking for.
