### ISSUE TITLE
Non-status 200 pages

### ISSUE THREAD

**Issue by imashnake0** [Splitties/refreshVersions#482]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

Some of the KDOC URLs link to non-status 200 pages.

## ⚠️ Current behavior

Links to pages that do not exist or that have been moved are present in KDOCs (only checked AndroidX):
~301 - https://developer.chrome.com/docs/android/custom-tabs~
404 - https://developer.android.com/reference/kotlin/androidx/compose/animation/res/package-summary
404 - https://developer.android.com/reference/kotlin/androidx/compose/animation/vector/package-summary
301 - https://developer.android.com/games/sdk
301 - https://developer.android.com/games/sdk/release-notes
~000 - https://dagger.dev/hilt~
404 - https://developer.android.com/reference/kotlin/androidx/navigation/dynamicfeatures/ui/package-summary
301 - https://developer.android.com/training/testing/additional-resources#samples
404 - https://developer.android.com/reference/kotlin/androidx/test/packages
301 - https://developer.android.com/training/testing/ui-testing/uiautomator-testing
301 - https://developer.android.com/training/testing/ui-automator
~404 - https://developer.android.com/reference/kotlin/androidx/test/uiautomator/package-summary~
~302 - https://issuetracker.google.com/issues/new?component=1077552&template=1598429~

## ✅ Expected behavior

All links work and their status is 200.

## 💣 Steps to reproduce

Open the link(s) and/or check the URL's status.

**Comment by jmfayard** [comment]
@imashnake0 wow thanks for the report.
Anyone is welcome to work on this

Just curious, did you do that manually? Seems like lots of tedious work.

**Comment by imashnake0** [comment]
@jmfayard I can try to take this on. Used a script :sunglasses:

**Comment by jmfayard** [comment]
Of course that would be great!

**Comment by LouisCAD** [comment]
Thank you @imashnake0!

I updated all the links that needed to, at last, they will make it into the next release.

BTW, there were some false positives in your list, and I'm not sure why. I crossed them in your original post.
