### ISSUE TITLE
mode VersionCatalogOnly still generates version.properties

### ISSUE THREAD

**Issue by ColtonIdle** [Splitties/refreshVersions#683]
- [ ] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
I'm trying to upgrade to using this plugin incrementally. The first step is to just move to version catalogs and THEN move to refreshVersions.

## ⚠️ Current behavior
 I use VersionCatalogOnly mode in a brand new android project, and it still generated a bunch of items in a new version.properties file

## ✅ Expected behavior
Don't generate version.properties file

## 💣 Steps to reproduce
Create a new project in AS, and run the steps here https://github.com/jmfayard/refreshVersions/wiki/RefreshVersions-%E2%99%A5%EF%B8%8F-Gradle-Version-Catalog but with VersionCatalogOnly and you'll see it still generates the version.properties.

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by LouisCAD** [comment]
True, duplicate. I'm closing this one.
