### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by aSemy** [Splitties/refreshVersions#691]
- [ ] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

^ that link 404s

## 🐛 Describe the bug

the `[Use the buildSrc](https://jmfayard.github.io/refreshVersions/gradle-buildsrcversions/)` link 404s

<img width="355" alt="image" src="https://github.com/Splitties/refreshVersions/assets/897017/40c50661-c8b9-4b32-b983-5a20ce06244c">

https://github.com/Splitties/refreshVersions/blob/8c4a699c123f871e7ff788a3cabc00b37757fd8f/README.md?plain=1#L16

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by LouisCAD** [comment]
Thanks for the heads-up.

I fixed all the links.
