### ISSUE TITLE
Clarification when using AndroidX.compose.bom

### ISSUE THREAD

**Issue by marcardar** [Splitties/refreshVersions#695]
In the androidx [compose documentation,](https://developer.android.com/jetpack/compose/bom) we are encouraged to use `platform`:

`implementation platform('androidx.compose:compose-bom:2023.06.01')`

However, in refreshVersion, it's not clear whether to use:

`api(AndroidX.compose.bom)`

or:

`api(platform(AndroidX.compose.bom))`

Both seem to work, but which one should be used?

**Comment by LouisCAD** [comment]
Hello, use `platform(…)`.
Are you sure it works without? Unless Gradle did something special, it wouldn't.

**Comment by LouisCAD** [comment]
I'm not sure what you mean by not configured correctly. You're properly using platform here.
