### ISSUE TITLE
Bug: property 'defaultVersionCatalogFile$refreshVersions_core' specifies file '${projectRoot}/gradle/libs.versions.toml' which doesn't exist

### ISSUE THREAD

**Issue by charles-santos-wd** [Splitties/refreshVersions#698]
- [x] I have read the [guidelines for submitting issues](https://splitties.github.io/refreshVersions/contributing/submitting-issues/#bug-reports)
## 🐛 Describe the bug
Upgraded from `0.51.0` to `0.60.0` and now trying to run `refreshVersions` fails.
My `refreshVersions` configuration is the following:
```kotlin
refreshVersions {
    @Suppress("UnstableApiUsage")
    rejectVersionIf {
        candidate.stabilityLevel isLessStableThan StabilityLevel.Stable
    }

    extraArtifactVersionKeyRules("""
        < some internal Workday group+artifact name rule which has never caused problems >
    """.trimIndent())
}
```
And I use only `versions.properties` — none of the Gradle version catalog stuff.

## ⚠️ Current behavior
Task `refreshVersions` fails:
```
> Task :refreshVersions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':refreshVersions' (type 'RefreshVersionsTask').
  - In plugin 'de.fayard.refreshVersions.core.RefreshVersionsCorePlugin' type 'de.fayard.refreshVersions.core.RefreshVersionsTask' property 'defaultVersionCatalogFile$refreshVersions_core' specifies file '/Users/charles.santos/code/yuzu-libs/gradle/libs.versions.toml' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.
    
    For more information, please refer to https://docs.gradle.org/8.2.1/userguide/validation_problems.html#input_file_does_not_exist in the Gradle documentation.
```

## ✅ Expected behavior
Task `refreshVersions` should do what it's expected to do — update my `versions.properties` file with dependency upgrades.

## 💣 Steps to reproduce
It looks like it's as simple as using just `versions.properties` in `0.51.0` and upgrading to `0.60.0`. I performed the upgrade in another one of my projects and I ran into the same failure.

Updated with reproduction repo:

Clone https://github.com/charles-santos-wd/refreshVersions-698 , and run `./gradlew refreshVersions`

## 📱 Tech info
No build scans as it's a private corporate repository 😞

## Workaround
Add
```kotlin
featureFlags {
    disable(FeatureFlag.VERSIONS_CATALOG)
}
```
to `refreshVersions { ... }` config in `settings.gradle.kts` to forcibly turn off the Version Catalog feature.

**Comment by LouisCAD** [comment]
Hello, which Gradle version are you running?

**Comment by charles-santos-wd** [comment]
Updated with a reproduction repo

**Comment by LouisCAD** [comment]
Should have written that I was able to reproduce myself. Fix incoming :)
