### ISSUE TITLE
Is it possible to retrieve the version through plugin?

### ISSUE THREAD

**Issue by charbgr** [Splitties/refreshVersions#704]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)

## ⚠️ Is your feature request related to a problem? Please describe
More of a question

## 💡 Describe the solution you'd like
Is is possible to retrieve the version of a library? 

e.g.  I have this versions.properties
```txt
version.firebase-crashlytics-gradle=2.9.2
##                      # available=2.9.3
##                      # available=2.9.4
##                      # available=2.9.5
```
And I want to find the version of `firebase-crashlytics-gradle`. Is this possible somehow? 

## 🤚 Do you want to develop this feature yourself?

- [ ] Yes
- [x] No

**Comment by LouisCAD** [comment]
Hello, pease, use discussions for questions, not issues. Yes, it's documented, you have `versionFor`.
